### ISSUE TITLE
minor bugs when making index

### ISSUE THREAD

**Issue by antonkulaga** [chhylp123/BitMapperBS#11]
When I make an index I have some minor bugs like:
```
rm: cannot remove 'tmp_ref.tmp.sa5': No such file or directory
```
Also, sometimes I get:
```
sh: 1: ./psascan: not found
```
when it is run inside of the bash script changes the current working folder. Unfortunately: I can only reproduce "psascan not found" with cromwell, cannot give a cromwell-independent example.

**Comment by chhylp123** [comment]
As for "sh: 1: ./psascan: not found", this problem is caused by bitmapperBS cannot find "psascan" binary. bitmapperBS utilizes "psascan" binary to build index, so the binary of "psascan" and the binary of "bitmapperBS" must be saved in the same folder. So you need to check if these two binaries are saved together.

As for the first problem, don't worry about this. Actually, this is not a bug. It just an output information.

**Comment by antonkulaga** [comment]
The problem is that psascan is indeed in thr same folder as bitmapperbs, at east in docker container. But for some reason if the working folder is changed (automatically by cromwell in my case)d it sometimes cannot find it. I suggest the following solution: if it cannot find psascan in the same folder, can it run it as a command ( I can add psascsn to the system path in docker container)

**Comment by chhylp123** [comment]
> The problem is that psascan is indeed in thr same folder as bitmapperbs, at east in docker container. But for some reason if the working folder is changed (automatically by cromwell in my case)d it sometimes cannot find it. I suggest the following solution: if it cannot find psascan in the same folder, can it run it as a command ( I can add psascsn to the system path in docker container)

ok, i will do it as you said.

**Comment by chhylp123** [comment]
> The problem is that psascan is indeed in thr same folder as bitmapperbs, at east in docker container. But for some reason if the working folder is changed (automatically by cromwell in my case)d it sometimes cannot find it. I suggest the following solution: if it cannot find psascan in the same folder, can it run it as a command ( I can add psascsn to the system path in docker container)

The problem has been solved. Please try the new version from github.
