### ISSUE TITLE
Use releases

### ISSUE THREAD

**Issue by supermaxiste** [chhylp123/BitMapperBS#12]
Hi,

I'll be planning on including BitMapperBS in a workflow and it would be great if releases were included to get an idea of the version that is used and new versions that come out.

Best,
Stefan

**Comment by chhylp123** [comment]
> Hi,
> 
> I'll be planning on including BitMapperBS in a workflow and it would be great if releases were included to get an idea of the version that is used and new versions that come out.
> 
> Best,
> Stefan

Hi Stefan,

May I ask what should I do exactly? Should I add an item on README to present the previous and future versions of BitMapperBS?

**Comment by supermaxiste** [comment]
Hi,

there's a feature on GitHub to create releases [here](https://help.github.com/en/articles/creating-releases). It's pretty easy to implement and it helps users to keep track of different versions of the same tool. I hope this clarified my issue!

Stefan

**Comment by chhylp123** [comment]
> Hi,
> 
> there's a feature on GitHub to create releases [here](https://help.github.com/en/articles/creating-releases). It's pretty easy to implement and it helps users to keep track of different versions of the same tool. I hope this clarified my issue!
> 
> Stefan

Thanks in advance. I will create a release as soon as possible. : )

**Comment by chhylp123** [comment]
> Hi,
> 
> there's a feature on GitHub to create releases [here](https://help.github.com/en/articles/creating-releases). It's pretty easy to implement and it helps users to keep track of different versions of the same tool. I hope this clarified my issue!
> 
> Stefan

Hi Stefan,

The releases have already included. Please let me know if you have any other problems.

**Comment by supermaxiste** [comment]
Thank you for the help,
the issue can be closed.
