### ISSUE TITLE
Anytools that can replace MethylDackel ?

### ISSUE THREAD

**Issue by zorrodong** [chhylp123/BitMapperBS#15]
Thanks for the wonderful tool to handle methylation datasets.

Since I have several problems when using MethylDackel, I wonder are there any other recommended tools to deal with the generated bam files?

Thank you very much and looking forward to your reply!

Best wishes,

Zorro
20190620

**Comment by chhylp123** [comment]
Hi Zorro,

I also found MethylExtract (https://bioinfo2.ugr.es/MethylExtract/index.html). But I haven't test it so I cannot make sure if it works well. In addition, BitMapperBS has its own methylation extract part. If you want to try, I can add docs for it. But please note that the methylation extract part of BitMapperBS does not use bam file. So maybe you cannot control the quality of the results by utilizing samtools.

BTW, may I ask what's the problem of MethylDackel? Maybe I can help you to solve them. I will make the methylation extract part of BitMapperBS better next week. But I'm busy this week to move to a new lab. So if you need BitMapperBS urgently, I still recommend MethylDackel.

Thanks a lot.


> Thanks for the wonderful tool to handle methylation datasets.
> 
> Since I have several problems when using MethylDackel, I wonder are there any other recommended tools to deal with the generated bam files?
> 
> Thank you very much and looking forward to your reply!
> 
> Best wishes,
> 
> Zorro
> 20190620

**Comment by zorrodong** [comment]
Thanks for the reply! Now I have it done successfully. Previously I lacked some libs. 

Best wishes,

Zorro

**Comment by zorrodong** [comment]
Sorry to bother you again. 

I wonder whether I can extract the ummaped pair-end reads in to a fastq file, and perform the single-end mapping mode? 

I find it will improve the mapping rate a little bit. Do you have any comments on this pipeline?

Looking forward to your reply!

Best wishes,

Zorro
20190622

**Comment by chhylp123** [comment]
I can add this feature in BitMapperBS this weekend. But I think mapping the unmapped PE reads in single-end mode may result incorrect alignment results. I’m not sure.

> Sorry to bother you again.
> 
> I wonder whether I can extract the ummaped pair-end reads in to a fastq file, and perform the single-end mapping mode?
> 
> I find it will improve the mapping rate a little bit. Do you have any comments on this pipeline?
> 
> Looking forward to your reply!
> 
> Best wishes,
> 
> Zorro
> 20190622

**Comment by chhylp123** [comment]
Sorry for late reply.

You can try the option '--unmapped_out'. With '--unmapped_out', the unmapped reads would be outputted to BAM file. After that, you can extract fastq from the BAM. Thanks.

> Sorry to bother you again.
> 
> I wonder whether I can extract the ummaped pair-end reads in to a fastq file, and perform the single-end mapping mode?
> 
> I find it will improve the mapping rate a little bit. Do you have any comments on this pipeline?
> 
> Looking forward to your reply!
> 
> Best wishes,
> 
> Zorro
> 20190622

**Comment by zorrodong** [comment]
Yeah, I have already done so. 

Thanks very much!
