### ISSUE TITLE
index parameter in --search is extremely confusing

### ISSUE THREAD

**Issue by antonkulaga** [chhylp123/BitMapperBS#8]
I see that the --index subcommand generated a lot of files
```
GRCh38.primary_assembly.genome.fa.index
GRCh38.primary_assembly.genome.fa.index.bs.index
GRCh38.primary_assembly.genome.fa.index.bs.index.bwt
GRCh38.primary_assembly.genome.fa.index.bs.index.occ
GRCh38.primary_assembly.genome.fa.index.bs.index.sa
GRCh38.primary_assembly.genome.fa.index.bs.pac
GRCh38.primary_assembly.genome.fa.index.methy
```
while in the
```
 /opt/BitMapperBS/bitmapperBS --search
```
the path to index is interpreted in a very weird way: instead of just taking a folder where the index is stored it gets a string to which it adds ".index" prefix and then starts searching for corresponding files. This is very confusing and creates a big headache for the real-world scenarios. Currently, most of the bioinformatic workflows are run by workflow managers that support either WDL or CWL workflow definitions standards. For example, the lab I belong to uses WDL standard with Cromwell as workflow running software, other labs use something else usually WLD/CWL compliant. However, in both WDL and CWL standards it is assumed that all bioinformatic tools are put to either docker or singularity containers (that is the reason why I created a docker for bitmapper) and all files are mounted to the containers with volumes. The path in the volume can be totally different than the path in the host system. If the tool uses either file or folder the paths differences between the container and the host system are handled easily by workflow management software, while for cases when I have to put a string which is then edited by the tool itself then workflow managers simply do not know what to mount as volumes.

So, here is what I suggest:
* --index command should generate a folder instead of putting a lot of files to the working folder
* --search command should receive a folder with index inside

**Comment by chhylp123** [comment]
> I see that the --index subcommand generated a lot of files
> 
> ```
> GRCh38.primary_assembly.genome.fa.index
> GRCh38.primary_assembly.genome.fa.index.bs.index
> GRCh38.primary_assembly.genome.fa.index.bs.index.bwt
> GRCh38.primary_assembly.genome.fa.index.bs.index.occ
> GRCh38.primary_assembly.genome.fa.index.bs.index.sa
> GRCh38.primary_assembly.genome.fa.index.bs.pac
> GRCh38.primary_assembly.genome.fa.index.methy
> ```
> while in the
> 
> ```
>  /opt/BitMapperBS/bitmapperBS --search
> ```
> the path to index is interpreted in a very weird way: instead of just taking a folder where the index is stored it gets a string to which it adds ".index" prefix and then starts searching for corresponding files. This is very confusing and creates a big headache for the real-world scenarios. Currently, most of the bioinformatic workflows are run by workflow managers that support either WDL or CWL workflow definitions standards. For example, the lab I belong to uses WDL standard with Cromwell as workflow running software, other labs use something else usually WLD/CWL compliant. However, in both WDL and CWL standards it is assumed that all bioinformatic tools are put to either docker or singularity containers (that is the reason why I created a docker for bitmapper) and all files are mounted to the containers with volumes. The path in the volume can be totally different than the path in the host system. If the tool uses either file or folder the paths differences between the container and the host system are handled easily by workflow management software, while for cases when I have to put a string which is then edited by the tool itself then workflow managers simply do not know what to mount as volumes.
> 
> So, here is what I suggest:
> 
> * --index command should generate a folder instead of putting a lot of files to the working folder
> * --search command should receive a folder with index inside
Thanks for your suggestions. I will release a new version as you suggestions today. Although bitmapperbs have already been used in BGI, I never try it with docker. Thanks very much for your great help! Have a good night.

PS: is bitmapperbs ran sucessfully without docker?

**Comment by chhylp123** [comment]
> I see that the --index subcommand generated a lot of files
> 
> ```
> GRCh38.primary_assembly.genome.fa.index
> GRCh38.primary_assembly.genome.fa.index.bs.index
> GRCh38.primary_assembly.genome.fa.index.bs.index.bwt
> GRCh38.primary_assembly.genome.fa.index.bs.index.occ
> GRCh38.primary_assembly.genome.fa.index.bs.index.sa
> GRCh38.primary_assembly.genome.fa.index.bs.pac
> GRCh38.primary_assembly.genome.fa.index.methy
> ```
> while in the
> 
> ```
>  /opt/BitMapperBS/bitmapperBS --search
> ```
> the path to index is interpreted in a very weird way: instead of just taking a folder where the index is stored it gets a string to which it adds ".index" prefix and then starts searching for corresponding files. This is very confusing and creates a big headache for the real-world scenarios. Currently, most of the bioinformatic workflows are run by workflow managers that support either WDL or CWL workflow definitions standards. For example, the lab I belong to uses WDL standard with Cromwell as workflow running software, other labs use something else usually WLD/CWL compliant. However, in both WDL and CWL standards it is assumed that all bioinformatic tools are put to either docker or singularity containers (that is the reason why I created a docker for bitmapper) and all files are mounted to the containers with volumes. The path in the volume can be totally different than the path in the host system. If the tool uses either file or folder the paths differences between the container and the host system are handled easily by workflow management software, while for cases when I have to put a string which is then edited by the tool itself then workflow managers simply do not know what to mount as volumes.
> 
> So, here is what I suggest:
> 
> * --index command should generate a folder instead of putting a lot of files to the working folder
> * --search command should receive a folder with index inside

Thanks for your suggestions. I will realese a new version as your said today. Although bitmapperbs has already been used in BGI, I never try it with docker. Thanks very much for your great help. Have a good night.

PS: is bitmapperbs ran sucessfully without docker?

**Comment by antonkulaga** [comment]
@chhylp123 yes, I got my first results with my docker container (the problem is that when I put it to WDL script with docker as the runtime there is a headache with paths). However, if we want to make an official docker container we have to agree to which account it will publish. I personally prefer https://quay.io/ to docker-hub as quay.io allows automatic builds whenever you make a commit to github ( here how the container looks like now https://quay.io/repository/comp-bio-aging/bit_mapper_bs if I PR it to your repository you will have to put it under your quay.io account). I can also push example WDL for those of BitMapperBS users who want to use it with WDL-based workflow engeines (like cromwell).
If any assistance with WDL or docker needed feel free to write to my WeChat, WhatsApp, FB, gitter or gmail (I am antonkulaga everywhere)

**Comment by chhylp123** [comment]
> @chhylp123 yes, I got my first results with my docker container (the problem is that when I put it to WDL script with docker as the runtime there is a headache with paths). However, if we want to make an official docker container we have to agree to which account it will publish. I personally prefer https://quay.io/ to docker-hub as quay.io allows automatic builds whenever you make a commit to github ( here how the container looks like now https://quay.io/repository/comp-bio-aging/bit_mapper_bs if I PR it to your repository you will have to put it under your quay.io account). I can also push example WDL for those of BitMapperBS users who want to use it with WDL-based workflow engeines (like cromwell).
> If any assistance with WDL or docker needed feel free to write to my WeChat, WhatsApp, FB, gitter or gmail (I am antonkulaga everywhere)

Cool, you have a WeChat ID. I will add you in WeChat. Thank you very much.

**Comment by antonkulaga** [comment]
After last update I consider it solved
